//
// Created by kathy on 12/6/2026.
//

#ifndef PROYECTO_LL_PROGRAMACION_LL_REPORTGENERATOR_H
#define PROYECTO_LL_PROGRAMACION_LL_REPORTGENERATOR_H



class ReportGenerator {

};



#endif //PROYECTO_LL_PROGRAMACION_LL_REPORTGENERATOR_H
